FROM node:latest

# Set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install and cache app dependencies
ADD package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@0.9.5 -g --silent

ADD typings.json /usr/src/app/typings.json
RUN npm install typings -g --silent
RUN typings install

# Start app
CMD ["npm", "start"]
