version: 2

jobs:
  run_tests:
    docker:
      - image: circleci/node:9.2.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install node dependencies
          command: npm install --silent

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install typings dependencies
          command: ./node_modules/.bin/typings install

      - run:
          name: Lint client
          command: npm run lint

  test_build:
    docker:
      - image: circleci/node:9.2.0

    environment:
      TAG: test

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Set COMMIT env var
          command: echo 'export COMMIT=${CIRCLE_SHA1::8}' >> $BASH_ENV

      - run:
          name: Build web service
          environment:
            CLIENT_SERVICE: metagenscope-client
            NODE_ENV: production
          command: |
            docker build . -t $CLIENT_SERVICE:$COMMIT

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - run_tests
      - test_build:
          requires:
            - run_tests
