import * as React from 'react';
import { Row, Col, Button, Modal } from 'react-bootstrap';
import { Link } from 'react-router-dom';

interface FooterModelState {
  showModal: boolean;
}

class Footer extends React.Component<{}, FooterModelState> {
  constructor(props: {}) {
    super(props);

    this.state = { showModal: false };

    this.open = this.open.bind(this);
    this.close = this.close.bind(this);
  }
  
  open() {
    this.setState({ showModal: true });
  }

  close() {
    this.setState({ showModal: false });
  }
    
  render() {
    return (
      <div>
        <Row>
          <Col lg={12}>
            <hr />
            <Button bsStyle="link" onClick={this.open}>About/Attributions/License</Button>
          </Col>
        </Row>

        <Modal show={this.state.showModal} onHide={this.close} bsSize="lg">
          <Modal.Header closeButton={true}>
            <Modal.Title>About/Attributions/License</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <p>StuckOnU is a 
              <Link to="http://www.masonlab.net/" target="_blank">Mason lab project</Link>
            </p>
            <p>For more info:
              <Link to="http://metasub.org/stuckonu/" target="_blank">http://metasub.org/stuckonu/</Link>
            </p>
            <p>Website &amp; visualizations by Cem Meydan and David Danko</p>
            <p>Sunburst plot by Kerry Rodden licensed under Apache License 2.0, modified for use</p>
            <p>Using plots from HighcartsJS under CC Attribution Non-Commercial License</p>
            <p>Voronoi scatter plot by TennisVisuals, licensed under the MIT license, modified for use</p>
            <p>RadarChart by Nadieh Bremer, modified for use</p>
            <p>Grouped bar plot by torresomar, modified for use</p>
            <p>All website logic (limited to the text content of *.html, *.js, *.css files) EXCLUDING the data("data"
              including but not limited to *.json, *.txt and figures, text, analyses and conclusions generated by those
              data either through this website or separately) is licensed under the MIT license.</p>
            <p>All of the data presented (including but not limited to *.json, *.txt and figures, text, analyses and
              conclusions generated by those data either through this website or separately) is restricted for use and
              requires explicit permission from the right holders. Raw data, processed results and figures will be
              publicly available and free to use once uploaded to the sequencing databases (pending necessary waivers).
              Please check <Link to="http://metasub.org/stuckonu/" target="_blank">http://metasub.org/stuckonu/</Link>
              to see when data is uploaded to a public database, or contact Dr.Christopher E. Mason for license.</p>
            <p>INDEMNIFICATION: Participant will indemnify, defend and hold harmless the International MetaSUB
              Consortium, Dr. Christopher Mason, JPMorgan, and affiliates from and against any and all losses, damages,
              liabilities, expenses and costs, caused by (a) accidental negligence or willful misconduct, or (b) the
              breach of any of the covenants, warranties and representations. Neither MetaSUB nor Dr. Mason is
              affiliated or associated with J.P. Morgan. Dr. Mason’s views, opinions, and results from this study are
              his own and do not necessarily reflect the views of J.P. Morgan.</p>
            <p>Copyright 2017 Mason Lab</p>
          </Modal.Body>
        </Modal>
      </div>
    );
  }
}
  
export default Footer;
  